In [79]:
#KIRUTHIKASHREE A

In [80]:
# 1Data importing

import pandas as pd
import numpy as np

dataset= pd.read_csv("C:/Users/kirut/OneDrive/Documents/crop_yield.csv")

In [81]:
# 2 head,tail
dataset.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [82]:
dataset.tail()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [83]:
#3 size, shape , column

dataset.size

196890

In [84]:
dataset.shape

(19689, 10)

In [85]:
dataset.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='str')

In [86]:
#4 handle missing vallues
dataset.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [87]:

dataset.dropna(inplace=True)

In [120]:
numeric=dataset.select_dtypes(include="number")

In [121]:
for col in dataset.select_dtypes(include="number").columns:
    dataset[col] = dataset[col].fillna(dataset[col].mean())

In [90]:
dataset.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [92]:
# 5 Remove duplicates
dataset.drop_duplicates(inplace=True)

In [93]:
dataset.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [94]:
dataset["Crop_Year"] = pd.to_datetime(
    dataset["Crop_Year"].astype(str),errors="coerce"
)

dataset["Crop_Year"].dtype

dtype('<M8[us]')

In [95]:
# 6loc
dataset.loc[0:4, ["Crop", "Crop_Year", "Production"]]

           Crop  Crop_Year  Production
0      Arecanut 1997-01-01       56708
1     Arhar/Tur 1997-01-01        4685
2   Castor seed 1997-01-01          22
3      Coconut  1997-01-01   126905000
4  Cotton(lint) 1997-01-01         794

In [96]:
dataset.iloc[0:5, 0:3]

           Crop  Crop_Year       Season
0      Arecanut 1997-01-01  Whole Year
1     Arhar/Tur 1997-01-01  Kharif
2   Castor seed 1997-01-01  Kharif
3      Coconut  1997-01-01  Whole Year
4  Cotton(lint) 1997-01-01  Kharif

In [102]:
# 7Filter base condition
dataset[dataset["Annual_Rainfall"] >2000]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_Per_Area
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891
2,Castor seed,1997-01-01,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331
4,Cotton(lint),1997-01-01,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584
...,...,...,...,...,...,...,...,...,...,...,...
19505,Other Kharif pulses,2012-01-01,Kharif,Goa,226.0,190,3048.9,34080.80,70.06,0.670000,0.840708
19506,Ragi,2012-01-01,Kharif,Goa,48.0,50,3048.9,7238.40,14.88,1.100000,1.041667
19507,Rice,2012-01-01,Kharif,Goa,31255.0,81229,3048.9,4713254.00,9689.05,2.590000,2.598912
19508,Rice,2012-01-01,Rabi,Goa,14575.0,41592,3048.9,2197910.00,4518.25,2.850000,2.853654
19509,Sugarcane,2012-01-01,Whole Year,Goa,854.0,46055,3048.9,128783.20,264.74,47.765000,53.928571

In [ ]:
dataset[dataset["Production"] > 1000]

In [98]:
#Create new column
dataset["Production_Per_Area"] = (dataset["Production"] / dataset["Area"]
)

In [71]:
dataset.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_Per_Area
0,Arecanut,NaT,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255
1,Arhar/Tur,NaT,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891
2,Castor seed,NaT,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638
3,Coconut,NaT,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331
4,Cotton(lint),NaT,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584

In [72]:
#9
dataset.groupby("Crop")["Production"].mean()

Crop
Arecanut                 2.416312e+05
Arhar/Tur                1.199091e+05
Bajra                    2.254524e+05
Banana                   9.243754e+05
Barley                   6.565214e+04
Black pepper             1.663214e+04
Cardamom                 3.452662e+03
Cashewnut                2.788960e+04
Castor seed              8.016404e+04
Coconut                  1.795070e+09
Coriander                1.629395e+04
Cotton(lint)             9.618307e+05
Cowpea(Lobia)            5.466963e+03
Dry chillies             6.207599e+04
Garlic                   7.519540e+04
Ginger                   5.474254e+04
Gram                     2.741160e+05
Groundnut                2.050018e+05
Guar seed                1.147227e+05
Horse-gram               1.422313e+04
Jowar                    2.766383e+05
Jute                     1.273060e+06
Khesari                  9.487269e+04
Linseed                  1.034926e+04
Maize                    4.214474e+05
Masoor                   6.087825e+04
Mesta                    6.691810e+04
Moong(Green Gram)        3.039255e+04
Moth                     8.306818e+03
Niger seed               2.116722e+05
Oilseeds total           6.046703e+05
Onion                    2.680638e+05
Other  Rabi pulses       1.813455e+04
Other Cereals            1.138260e+04
Other Kharif pulses      1.373407e+04
Other Summer Pulses      8.394000e+02
Peas & beans (Pulses)    3.878187e+04
Potato                   1.002688e+06
Ragi                     8.878707e+04
Rapeseed &Mustard        1.480093e+05
Rice                     1.862407e+06
Safflower                1.918219e+04
Sannhamp                 2.624294e+03
Sesamum                  1.977076e+04
Small millets            2.768919e+04
Soyabean                 5.491681e+05
Sugarcane                1.196122e+07
Sunflower                3.320780e+04
Sweet potato             3.813018e+04
Tapioca                  6.511676e+05
Tobacco                  5.792230e+04
Turmeric                 2.875055e+04
Urad                     4.811537e+04
Wheat                    3.322485e+06
other oilseeds           7.962836e+04
Name: Production, dtype: float64

In [75]:
#10 lbl encode
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dataset["Crop_Encoded"] = le.fit_transform(dataset["Crop"])
dataset.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_Per_Area,Crop_Encoded
0,Arecanut,NaT,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255,0
1,Arhar/Tur,NaT,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891,1
2,Castor seed,NaT,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638,8
3,Coconut,NaT,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,9
4,Cotton(lint),NaT,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584,11

In [103]:
# 11 One-Hot Encoding
dataset = pd.get_dummies(
    dataset, columns=["Season"]
)

dataset.head()

,Crop,Crop_Year,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_Per_Area,Season_Autumn,Season_Kharif,Season_Rabi,Season_Summer,Season_Whole Year,Season_Winter
0,Arecanut,1997-01-01,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255,False,False,False,False,True,False
1,Arhar/Tur,1997-01-01,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891,False,True,False,False,False,False
2,Castor seed,1997-01-01,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638,False,True,False,False,False,False
3,Coconut,1997-01-01,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,False,False,False,False,True,False
4,Cotton(lint),1997-01-01,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584,False,True,False,False,False,False

In [107]:
# 12 Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
ordi= OrdinalEncoder()

dataset[["State_Encoded"]] =ordi.fit_transform(dataset[["State"]]
)

dataset.head()

,Crop,Crop_Year,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_Per_Area,Season_Autumn,Season_Kharif,Season_Rabi,Season_Summer,Season_Whole Year,Season_Winter,State_Encoded
0,Arecanut,1997-01-01,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255,False,False,False,False,True,False,2.0
1,Arhar/Tur,1997-01-01,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891,False,True,False,False,False,False,2.0
2,Castor seed,1997-01-01,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638,False,True,False,False,False,False,2.0
3,Coconut,1997-01-01,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,False,False,False,False,True,False,2.0
4,Cotton(lint),1997-01-01,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584,False,True,False,False,False,False,2.0

In [109]:
result=pd.DataFrame({
    "Mean": numeric.mean(),
    "Median": numeric.median(),
    "Mode": numeric.mode().iloc[0]
})
print(result,round(3))

                         Mean      Median       Mode
Crop_Year        2.009128e+03     2010.00  2019.0000
Area             1.799266e+05     9317.00     1.0000
Production       1.643594e+07    13804.00     0.0000
Annual_Rainfall  1.437755e+03     1247.60  1434.5875
Fertilizer       2.410331e+07  1234957.44   150.8000
Pesticide        4.884835e+04     2421.90     0.9900
Yield            7.995401e+01        1.03     1.0000 3

In [116]:
#14 std and Variance
result1= dataset["Production"].dropna()

print("Standard Deviation:",numeric.std())

print("Variance:",numeric.var())

Standard Deviation: Crop_Year          6.498099e+00
Area               7.328287e+05
Production         2.630568e+08
Annual_Rainfall    8.169096e+02
Fertilizer         9.494600e+07
Pesticide          2.132874e+05
Yield              8.783062e+02
dtype: float64
Variance: Crop_Year          4.222529e+01
Area               5.370379e+11
Production         6.919890e+16
Annual_Rainfall    6.673413e+05
Fertilizer         9.014744e+15
Pesticide          4.549150e+10
Yield              7.714218e+05
dtype: float64

In [117]:
#15range
result2=pd.DataFrame({
    "Minimum": numeric.min(),
    "Maximum": numeric.max(),
    "Range": numeric.max()-numeric.min()
        })
print(result2.astype(int))

                 Minimum     Maximum       Range
Crop_Year           1997        2020          23
Area                   0    50808100    50808099
Production             0  6326000000  6326000000
Annual_Rainfall      301        6552        6251
Fertilizer            54  4835406877  4835406822
Pesticide              0    15750511    15750510
Yield                  0       21105       21105

In [119]:
# 16Quartile
result3 = pd.DataFrame({
    "Q1(25%)": numeric.quantile(0.25),
    "Q2(50%)": numeric.quantile(0.50),
    "Q3(75%)": numeric.quantile(0.75),
})

result3["IQR"] = result3["Q3(75%)"] - result3["Q1(25%)"]

print(result3)

                   Q1(25%)     Q2(50%)       Q3(75%)           IQR
Crop_Year          2004.00     2010.00  2.015000e+03  1.100000e+01
Area               1390.00     9317.00  7.511200e+04  7.372200e+04
Production         1393.00    13804.00  1.227180e+05  1.213250e+05
Annual_Rainfall     940.70     1247.60  1.643700e+03  7.030000e+02
Fertilizer       188014.62  1234957.44  1.000385e+07  9.815833e+06
Pesticide           356.70     2421.90  2.004170e+04  1.968500e+04
Yield                 0.60        1.03  2.388889e+00  1.788889e+00

In [123]:
#17Skewness
result4 = pd.DataFrame({
    "Skewness": numeric.skew()
})

print(result4)

                      Skewness
Area                 21.858218
Production           19.299193
Annual_Rainfall       2.131785
Fertilizer           13.412599
Pesticide            25.635746
Yield                12.785265
Production_Per_Area  12.807936
State_Encoded         0.050369

In [124]:
#18 Kurtosis
result5 = pd.DataFrame({
    "Kurtosis": numeric.kurt()
})

print(result5)

                        Kurtosis
Area                 1202.624968
Production            388.567239
Annual_Rainfall         6.974983
Fertilizer            408.454102
Pesticide            1546.727623
Yield                 175.577323
Production_Per_Area   175.791312
State_Encoded          -1.174046

In [125]:
# IQR
Q1 = numeric.quantile(0.25)
Q3 = numeric.quantile(0.75)

IQR = Q3 - Q1
lower_limit = Q1 - 1.5 * IQR
Upper_limit = Q3 + 1.5 * IQR

outliers = (
    (numeric < lower_limit) | (numeric > Upper_limit)
)
print("Lower Bound:\n", lower_limit)
print("Upper Bound:\n", Upper_limit)
print("Outlier in each column:\n", numeric[outliers].count())

Lower Bound:
 Area                  -1.091930e+05
Production            -1.805945e+05
Annual_Rainfall       -1.138000e+02
Fertilizer            -1.453573e+07
Pesticide             -2.917080e+04
Yield                 -2.083333e+00
Production_Per_Area   -2.205453e+00
State_Encoded         -1.550000e+01
dtype: float64
Upper Bound:
 Area                   1.856950e+05
Production             3.047055e+05
Annual_Rainfall        2.698200e+03
Fertilizer             2.472760e+07
Pesticide              4.956920e+04
Yield                  5.072222e+00
Production_Per_Area    5.264689e+00
State_Encoded          4.450000e+01
dtype: float64
Outlier in each column:
 Area                   3076
Production             3373
Annual_Rainfall        1527
Fertilizer             3093
Pesticide              3036
Yield                  3065
Production_Per_Area    3003
State_Encoded             0
dtype: int64

In [129]:
# Cv
mean_values = numeric.mean()
std_values = numeric.std()

result6 = pd.DataFrame({
    "Mean": mean_values,
    "Standard Deviation": std_values,
    "CV (%)": (std_values / mean_values) * 100
})
print(result6.round(3))

                             Mean  Standard Deviation    CV (%)
Area                 1.799266e+05        7.328287e+05   407.293
Production           1.643594e+07        2.630568e+08  1600.498
Annual_Rainfall      1.437755e+03        8.169100e+02    56.818
Fertilizer           2.410331e+07        9.494600e+07   393.913
Pesticide            4.884835e+04        2.132874e+05   436.632
Yield                7.995400e+01        8.783060e+02  1098.514
Production_Per_Area  8.384100e+01        9.235970e+02  1101.608
State_Encoded        1.432900e+01        9.000000e+00    62.814

In [130]:
# Compare Mean and Median to Identify Skewness
result7 = pd.DataFrame({
    "Mean": numeric.mean(),
    "Median": numeric.median()
})

result7["Skewness"] = "Symmetric"
result7.loc[result7["Mean"] > result7["Median"], "Skewness"] = "Positive Skewness"
result7.loc[result7["Mean"] < result7["Median"], "Skewness"] = "Negative Skewness"

print(result7.round(3))

                             Mean       Median           Skewness
Area                 1.799266e+05     9317.000  Positive Skewness
Production           1.643594e+07    13804.000  Positive Skewness
Annual_Rainfall      1.437755e+03     1247.600  Positive Skewness
Fertilizer           2.410331e+07  1234957.440  Positive Skewness
Pesticide            4.884835e+04     2421.900  Positive Skewness
Yield                7.995400e+01        1.030  Positive Skewness
Production_Per_Area  8.384100e+01        1.036  Positive Skewness
State_Encoded        1.432900e+01       14.000  Positive Skewness