In [108]:
#KIRUTHIKASHREE A

In [109]:
#1Data importing
import pandas as pd
import matplotlib.pyplot as plt

In [110]:
dataset=pd.read_csv("C:/Users/kirut/OneDrive/Documents/load_forecasting_dataset_corrected.csv")

In [148]:
data=pd.read_csv("C:/Users/kirut/OneDrive/Documents/Shopping_Customer_Dataset (1).csv")

In [111]:
#2 first 5 row, last5
dataset.head()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
0,1/1/2020 0:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2,0,1,Summer,0,1599.342831
1,1/1/2020 0:15,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2,0,1,Summer,0,1472.347140
2,1/1/2020 0:30,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2,0,1,Summer,0,1629.537708
3,1/1/2020 0:45,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971
4,1/1/2020 1:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2,1,1,Summer,0,1453.169325

In [112]:
dataset.tail()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
189883,5/31/2025 22:45,27.433177,82.943227,1.564385,0.476854,214.276578,986.122824,487.823955,17.183842,5,22,5,Fall,0,1443.317681
189884,5/31/2025 23:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,23,5,Fall,0,1908.512650
189885,5/31/2025 23:15,27.620201,87.091108,2.722335,1.422315,282.487744,1007.429961,509.295868,24.883951,5,23,5,Fall,0,1462.020111
189886,5/31/2025 23:30,29.378415,75.743129,2.317605,9.383305,246.291089,1019.239724,536.514530,27.765615,5,23,5,Fall,0,1637.841485
189887,5/31/2025 23:45,27.737078,83.529497,0.914573,9.901955,299.088224,1020.425273,518.742211,15.496762,5,23,5,Fall,0,1473.707828

In [113]:
#3Size,shape, column name
dataset.size

2848320

In [114]:
dataset.shape

(189888, 15)

In [115]:
dataset.columns

Index(['Timestamp', 'Temperature (°C)', 'Humidity (%)', 'Wind Speed (m/s)',
       'Rainfall (mm)', 'Solar Irradiance (W/m²)', 'GDP (LKR)',
       'Per Capita Energy Use (kWh)', 'Electricity Price (LKR/kWh)',
       'Day of Week', 'Hour of Day', 'Month', 'Season', 'Public Event',
       'Load Demand (kW)'],
      dtype='str')

In [116]:
#4 handle missing values
dataset.dropna(inplace=True)
numeric=dataset.select_dtypes(include="number")
result=pd.DataFrame({
    "Mean":numeric.mean(),
    "Median":numeric.median(),
    "Mode":numeric.mode().iloc[0]
})
print(result.round(2))

                                Mean   Median     Mode
Temperature (°C)               28.00    28.00    26.04
Humidity (%)                   80.00    80.00    73.83
Wind Speed (m/s)                2.00     2.00     1.25
Rainfall (mm)                   5.01     3.48     0.91
Solar Irradiance (W/m²)       249.94   249.87   183.47
GDP (LKR)                    1000.08  1000.00   950.47
Per Capita Energy Use (kWh)   499.91   499.95   468.02
Electricity Price (LKR/kWh)    25.00    25.01    21.15
Day of Week                     3.00     3.00     2.00
Hour of Day                    11.50    11.50     0.00
Month                           6.25     6.00     1.00
Public Event                    0.05     0.00     0.00
Load Demand (kW)             1500.15  1500.27  1303.52

In [117]:
#remove duplicate
dataset.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
189883    False
189884    False
189885    False
189886    False
189887    False
Length: 189888, dtype: bool

In [118]:
dataset["Timestamp"].dtype

dataset["Timestamp"] = pd.to_datetime(
    dataset["Timestamp"], errors="coerce")
dataset.tail()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
189883,2025-05-31 22:45:00,27.433177,82.943227,1.564385,0.476854,214.276578,986.122824,487.823955,17.183842,5,22,5,Fall,0,1443.317681
189884,2025-05-31 23:00:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,23,5,Fall,0,1908.512650
189885,2025-05-31 23:15:00,27.620201,87.091108,2.722335,1.422315,282.487744,1007.429961,509.295868,24.883951,5,23,5,Fall,0,1462.020111
189886,2025-05-31 23:30:00,29.378415,75.743129,2.317605,9.383305,246.291089,1019.239724,536.514530,27.765615,5,23,5,Fall,0,1637.841485
189887,2025-05-31 23:45:00,27.737078,83.529497,0.914573,9.901955,299.088224,1020.425273,518.742211,15.496762,5,23,5,Fall,0,1473.707828

In [122]:
#6select rows
dataset.loc[0:5,["Temperature (°C)", "Humidity (%)"]]

   Temperature (°C)  Humidity (%)
0         28.993428     75.011269
1         27.723471     77.024015
2         29.295377     74.732958
3         31.046060     87.615995
4         27.531693     79.709858
5         27.531726     79.342322

In [124]:
dataset.iloc[0:5, 0:5]

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm)
0,2020-01-01 00:00:00,28.993428,75.011269,1.053861,4.140513
1,2020-01-01 00:15:00,27.723471,77.024015,1.085152,9.446997
2,2020-01-01 00:30:00,29.295377,74.732958,3.363800,4.265813
3,2020-01-01 00:45:00,31.046060,87.615995,2.539148,1.038103
4,2020-01-01 01:00:00,27.531693,79.709858,1.366819,4.201393

In [127]:
#Filter base condition
dataset[dataset["Temperature (°C)"]>30]

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
3,2020-01-01 00:45:00,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971
6,2020-01-01 01:30:00,31.158426,71.645943,0.880808,0.544923,247.400541,800.427592,496.439128,23.220658,2,1,1,Summer,0,1815.842563
20,2020-01-01 05:00:00,30.931298,79.069137,2.220157,0.590995,346.914079,1020.113954,437.718781,18.661290,2,5,1,Summer,0,1793.129754
31,2020-01-01 07:45:00,31.704556,77.503728,4.163454,4.474810,188.232456,1044.173259,516.044985,29.882956,2,7,1,Summer,0,1870.455637
47,2020-01-01 11:45:00,30.114244,73.177316,2.983434,3.167322,243.501696,1008.757961,460.585722,32.577152,2,11,1,Summer,0,1711.424445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189822,2025-05-31 07:30:00,30.480822,83.304663,2.161117,2.663962,156.201382,1026.612649,502.902113,26.768375,5,7,5,Fall,0,1748.082199
189842,2025-05-31 12:30:00,31.204236,81.552859,2.523163,1.832681,226.244507,959.194726,520.320373,30.877635,5,12,5,Fall,0,1820.423589
189843,2025-05-31 12:45:00,30.283227,71.145064,2.298914,5.383897,334.858099,961.743935,517.627900,36.739025,5,12,5,Fall,0,1728.322663
189864,2025-05-31 18:00:00,30.280022,78.614448,1.835867,4.513671,253.320492,995.628566,458.917058,26.370144,5,18,5,Fall,0,1728.002235
189884,2025-05-31 23:00:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,23,5,Fall,0,1908.512650

In [137]:
#8newcolumn
dataset["Weather"]=dataset["Temperature (°C)"]+ dataset["Humidity (%)"]
dataset.head()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW),weather,Weather
0,2020-01-01 00:00:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2,0,1,Summer,0,1599.342831,104.004697,104.004697
1,2020-01-01 00:15:00,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2,0,1,Summer,0,1472.347140,104.747487,104.747487
2,2020-01-01 00:30:00,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2,0,1,Summer,0,1629.537708,104.028335,104.028335
3,2020-01-01 00:45:00,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971,118.662055,118.662055
4,2020-01-01 01:00:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2,1,1,Summer,0,1453.169325,107.241551,107.241551

In [139]:
#9groupby
dataset.groupby("Season")["Temperature (°C)"].mean()

Season
Fall      28.003603
Summer    28.001089
Winter    27.997543
Name: Temperature (°C), dtype: float64

In [143]:
#lbl encode
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [144]:
lbl=LabelEncoder()
dataset["Season_1"]=lbl.fit_transform(dataset["Season"])

dataset.tail()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW),weather,Weather,Season_Encoded,Season_1
189883,2025-05-31 22:45:00,27.433177,82.943227,1.564385,0.476854,214.276578,986.122824,487.823955,17.183842,5,22,5,Fall,0,1443.317681,110.376404,110.376404,0,0
189884,2025-05-31 23:00:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,23,5,Fall,0,1908.512650,116.245071,116.245071,0,0
189885,2025-05-31 23:15:00,27.620201,87.091108,2.722335,1.422315,282.487744,1007.429961,509.295868,24.883951,5,23,5,Fall,0,1462.020111,114.711309,114.711309,0,0
189886,2025-05-31 23:30:00,29.378415,75.743129,2.317605,9.383305,246.291089,1019.239724,536.514530,27.765615,5,23,5,Fall,0,1637.841485,105.121544,105.121544,0,0
189887,2025-05-31 23:45:00,27.737078,83.529497,0.914573,9.901955,299.088224,1020.425273,518.742211,15.496762,5,23,5,Fall,0,1473.707828,111.266575,111.266575,0,0

In [145]:
#onehot
dataset = pd.get_dummies(dataset,columns=["Season"])
dataset.tail()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,...,Month,Public Event,Load Demand (kW),weather,Weather,Season_Encoded,Season_1,Season_Fall,Season_Summer,Season_Winter
189883,2025-05-31 22:45:00,27.433177,82.943227,1.564385,0.476854,214.276578,986.122824,487.823955,17.183842,5,...,5,0,1443.317681,110.376404,110.376404,0,0,True,False,False
189884,2025-05-31 23:00:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,...,5,0,1908.512650,116.245071,116.245071,0,0,True,False,False
189885,2025-05-31 23:15:00,27.620201,87.091108,2.722335,1.422315,282.487744,1007.429961,509.295868,24.883951,5,...,5,0,1462.020111,114.711309,114.711309,0,0,True,False,False
189886,2025-05-31 23:30:00,29.378415,75.743129,2.317605,9.383305,246.291089,1019.239724,536.514530,27.765615,5,...,5,0,1637.841485,105.121544,105.121544,0,0,True,False,False
189887,2025-05-31 23:45:00,27.737078,83.529497,0.914573,9.901955,299.088224,1020.425273,518.742211,15.496762,5,...,5,0,1473.707828,111.266575,111.266575,0,0,True,False,False

In [149]:
data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [154]:
Ord = OrdinalEncoder(categories=[["Bronze", "Silver", "Premium"]])

data["Level"] = Ord.fit_transform(data[["Membership_Level"]])

data.tail()

ValueError: Found unknown categories ['Gold'] in column 0 during fit